STREAMS-2330 add initialValue section
Axway/streams-open-docs pull request #135
Opened 2022-01-03 15:27 UTC by dominiquemongelli

Thank you for your contribution to the Axway Streams documentation.

## Describe the changes

Update section in publisher http poller about new attribute initialValue.

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

2022-01-04 13:35 UTC, epiasentin-axway requested changes

2022-01-04 13:35 UTC, epiasentin-axway commented on content/en/docs/publishers/publisher-http-poller.md
> +| initialValue | no  |                       | DateTime of the first request made by the publisher http poller. Must follow `pattern` format |
use 'HTTP poller publisher' instead of  'publisher http poller'

2022-01-04 13:35 UTC, epiasentin-axway commented on content/en/docs/publishers/publisher-http-poller.md
> +| initialValue    | no  |  | Timestamp of the first request made by the http poller publisher. In milliseconds or seconds, depending on `useMilliseconds` attribute |
idem use 'HTTP poller publisher' to be coherent with the other sections

2022-01-04 13:40 UTC, epiasentin-axway commented on content/en/docs/publishers/publisher-http-poller.md
> +              "initialValue": "1641290851"
use "initialValue": 1641290851 instead

2022-01-04 13:41 UTC, epiasentin-axway commented on content/en/docs/publishers/publisher-http-poller.md
> +              "initialValue": "1641224429000"
idem here use : "initialValue": 1641224429000

2022-01-04 18:30 UTC, epiasentin-axway commented
There is no example of Datetime CDC with intialValue

2022-01-05 08:54 UTC, guillaumelamirand commented on content/en/docs/publishers/publisher-http-poller.md
> +| initialValue | no  |                       | DateTime of the first request made by the publisher http poller. Must follow `pattern` format |
Align the description with timestamp section : "publisher http poller" vs "http poller publisher"

2022-01-05 08:55 UTC, guillaumelamirand commented on content/en/docs/publishers/publisher-http-poller.md
> +| initialValue | no  |                       | DateTime of the first request made by the publisher http poller. Must follow `pattern` format |
I would say "DateTime used for the first request"

2022-01-05 08:55 UTC, guillaumelamirand commented on content/en/docs/publishers/publisher-http-poller.md
> +| initialValue    | no  |  | Timestamp of the first request made by the http poller publisher. In milliseconds or seconds, depending on `useMilliseconds` attribute |
I would say "Timestamp used for the first request"

2022-01-05 10:12 UTC, guillaumelamirand approved these changes

2022-01-05 10:30 UTC, epiasentin-axway approved these changes

2022-01-05 10:40 UTC, epiasentin-axway commented
@andreamussap could you please review this PR ?

2022-01-05 12:28 UTC, andreamussap commented on content/en/docs/publishers/publisher-http-poller.md
>  Format the reference value as DateTime. This must follow the [Java DateTimeFormatter](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/format/DateTimeFormatter.html#patterns) pa
(Format the reference value as DateTime) - You can or you must format the reference? Better to add this information to make it clear.

2022-01-05 12:28 UTC, andreamussap commented on content/en/docs/publishers/publisher-http-poller.md
> +The following is an example of how to dynamically add a `from` query parameter to the target URL based on the **last-success** reference with the following format `yyyy-MM-dd'T'HH:mm:ss`, by using th
please use code (` `) for the  last-success reference as opposed to bold styling.

2022-01-05 12:31 UTC, andreamussap commented on content/en/docs/publishers/publisher-http-poller.md
> +Due to the configured `initialValue`, the first resulting target URL will be : `https://myserver/my-api?from=2021-31-10'T'12:00:00`.
Please update to - Based on the configured `initialValue`, the first resulting URL target will be `placeholder`, and the subsequent resulting targets will look like `placeholder`

2022-01-05 12:33 UTC, andreamussap commented on content/en/docs/publishers/publisher-http-poller.md
> +{{< alert color="info" >}}
please update the alert - {{< alert title="Note" >}}

2022-01-05 12:33 UTC, andreamussap commented on content/en/docs/publishers/publisher-http-poller.md
> +{{< alert color="info" >}}
please update the alert - {{< alert title="Note" >}}

2022-01-05 13:45 UTC, andreamussap commented on content/en/docs/publishers/publisher-http-poller.md
>  #### Timestamp format
shouldn't this be at the same level (H3) as the 'DateTime format' heading?

2022-01-05 13:56 UTC, andreamussap commented on content/en/docs/publishers/publisher-http-poller.md
> +| useMilliseconds | no  | false | If true, the time stamp is measured in milliseconds, otherwise in seconds.                                                                  |
time stamp -> timestamp (one word)

2022-01-05 13:59 UTC, andreamussap commented on content/en/docs/publishers/publisher-http-poller.md
> +| initialValue    | no  |  | Timestamp used for the first request made by the HTTP poller publisher. In milliseconds or seconds, depending on `useMilliseconds` attribute |
...publisher, in milliseconds or seconds, depending on what is configured in the `useMilliseconds` attribute

2022-01-05 14:01 UTC, andreamussap commented on content/en/docs/publishers/publisher-http-poller.md
> +Due to the configured `initialValue`, the first resulting target URL will be : `https://myserver/my-api?from=1641290851`.
Please update to - Based on the configured `initialValue`, the first resulting URL target will be `placeholder`, and the subsequent resulting targets will look like `placeholder`

2022-01-05 16:59 UTC, merged