nginx migration to 1.1.1
Axway/streams-open-docs pull request #144
Opened 2022-01-27 14:41 UTC by dominiquemongelli

Thank you for your contribution to the Axway Streams documentation.

## Describe the changes

Nginx ingress controller migration to version 1.1.1

https://deploy-preview-144--streams-open-docs.netlify.app/docs/install/
https://deploy-preview-144--streams-open-docs.netlify.app/docs/relnotes/20220228_streams_relnotes/
https://deploy-preview-144--streams-open-docs.netlify.app/docs/architecture/#nginx

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

2022-01-28 14:13 UTC, andreamussap commented on content/en/docs/relnotes/20220228_streams_relnotes.md
> +Due to the migration to nginx in version `1.1.1`, the minimum version of kubernetes supported is `1.1.19`.
```suggestion
As a result of the Nginx library update to version `1.1.1`, the minimum supported version of Kubernetes is now `1.1.19`.
```

2022-02-09 09:34 UTC, cremond commented
Looks good to me from a technical standpoint. Ready for your review @andreamussap

2022-02-09 14:05 UTC, andreamussap commented on content/en/docs/relnotes/20220228_streams_relnotes.md
> +## Important changes
Don't you want to inform about the release of Salesforce Publisher beta feature?

2022-02-11 14:04 UTC, rbissey-axway approved these changes
Looks good to me.

2022-02-11 15:14 UTC, cremond approved these changes
The "downtime" documentation was short lived, but it's because we fixed it :) Looks good to me.

2022-02-11 15:27 UTC, guillaumelamirand commented on content/en/docs/install/_index.md
> +To use your Kubernetes Secret in the registry, add the Secret's name in the `imagePullSecrets` array. For example, add `--set imagePullSecrets[0].name="${REGISTRY_SECRET_NAME}"` to the Helm chart ins
The precision about how to customize imagePullSecrets shouldn't be added here and is explained in a dedicated section: https://develop--streams-open-docs.netlify.app/docs/install/customize-install/#options-to-manage-helm-parameters

2022-02-11 15:31 UTC, guillaumelamirand requested changes
See comment about --set

2022-02-11 16:28 UTC, guillaumelamirand approved these changes

2022-02-14 11:11 UTC, merged