Streams 2639
Axway/streams-open-docs pull request #156
Opened 2022-04-19 15:35 UTC by rbissey-axway

Thank you for your contribution to the Axway Streams documentation.

## Describe the changes

Enter a brief description of your changes here to communicate to the maintainers what you changed and why.

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

2022-05-05 12:35 UTC, epiasentin-axway requested changes

2022-05-05 12:35 UTC, epiasentin-axway commented on content/en/docs/subscribers/subscriber-sse.md
> +
Missing explanation of the advantages of provisioning a subscription. (ie different lifecycle vs regular subscription mode)

2022-05-05 12:35 UTC, epiasentin-axway commented on content/en/docs/subscribers/subscriber-sse.md
see my last comment, need to explain that in the case a subscription will delete when the consumer disconnect

2022-05-06 12:45 UTC, andreamussap commented
Editorial review is done. @jjayet-axway please review/approve so I can merge the PR. Thank you.

2022-05-11 13:42 UTC, merged