STREAMS-1649 subscriber kafka securely connection to external kafka broker
Axway/streams-open-docs pull request #157
Opened 2022-04-20 09:50 UTC by dominiquemongelli

Thank you for your contribution to the Axway Streams documentation.

## Describe the changes

Add authorization configuration in subscriber kafka for securing connection with external kafka broker

https://deploy-preview-157--streams-open-docs.netlify.app/docs/subscribers/subscriber-kafka/
https://deploy-preview-157--streams-open-docs.netlify.app/docs/relnotes/20220530_streams_relnotes/
https://deploy-preview-157--streams-open-docs.netlify.app/docs/subscribers/subscriber-webhook/

## Checklist for contributors

Before submitting this PR, please make sure:

* [x] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [x] You have signed the [Axway CLA](https://cla.axway.com/)
* [x] You have verified the technical accuracy of your change
* [x] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [x] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

2022-04-21 16:29 UTC, cremond requested changes

2022-04-21 16:29 UTC, cremond commented on content/en/docs/subscribers/subscriber-kafka.md
> +### Authorization with Sasl and SSL
Is it not authentication instead?(part of the SASL acronym, I think ^^)

2022-04-21 16:29 UTC, cremond commented on content/en/docs/subscribers/subscriber-kafka.md
> +In case you need to add a custom certificate for connection with the external kafka broker:
I think we'll nearly always be adding the self-signed root certficateauthority, not the individual certificates themselves. Is it possible to make this clearer in thes instructions ?

2022-04-21 16:29 UTC, cremond commented on content/en/docs/subscribers/subscriber-kafka.md
> +{{< alert title="Caution" >}}Adding custom certificate is not recommended for production environment.{{< /alert >}}
Is it really the case? I know it is for TLS for http api as we don't want random customers online to have to trust random public keys, but I don't see quite the same use case for Kafka. Especially when it is doubled with authentication anyways

2022-04-21 16:29 UTC, cremond commented on content/en/docs/subscribers/subscriber-kafka.md
> +* Follow the dedicated section [Add self-signed TLS certificates](/docs/install/#add-self-signed-tls-certificates) to add the custom certificate
Could we add an "(or ask your operator to do it if you are not operating streams yourself)" or something here to make it clear this will not be an api call, but require cluster access and more or less admin rights?

2022-04-22 12:50 UTC, cremond commented on content/en/docs/subscribers/subscriber-kafka.md
> +In case you need to add a root certificate authority for connection with the external kafka broker:
```suggestion
With `SSL` enabled, Streams needs to trust the root certificate authority that signed your kafka broker certificates. If you are not using one of the generic `SSL` certificates providers (e.g. Digicert, Let's Encrypt...), but a custom root certificate authority instead, you must add it to Streams:
```

2022-04-22 12:50 UTC, cremond commented on content/en/docs/subscribers/subscriber-kafka.md
> +
```suggestion

```

2022-04-22 13:07 UTC, cremond approved these changes
looks good to me now :)

2022-05-05 16:37 UTC, cremond commented
@jjayet-axway could you give this a final review before we merge? Thanks :)

2022-05-06 16:31 UTC, jjayet-axway approved these changes

2022-05-10 11:19 UTC, merged