add security guide section
Axway/streams-open-docs pull request #24
Opened 2020-10-12 08:51 UTC by dominiquemongelli

Thank you for your contribution to the Axway Streams documentation.

## Describe the changes

Add security guide section

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

## Checklist for approvers

_This section is to be filled out by project maintainers only._

Before approving this PR, please make sure it:

* [ ] Does not have conflicts with the base branch
* [ ] Is believed to be accurate (technical accuracy to be checked with an SME for PRs originating from outside R&D)
* [ ] Follows [Axway style](https://techweb.axway.com/confluence/display/RIE/Style+guide)
* [ ] Follows [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)
* [ ] Follows [best practices](https://axway-open-docs.netlify.com/docs/contribution_guidelines/bestpracticedevdoc/)
* [ ] Does not contain typos, grammatical errors, etc.
* [ ] Does not expose any sensitive information
* [ ] Passes the Markdown linter rules (automated via CI check)
* [ ] Does not contain broken links

2020-10-12 09:40 UTC, allandenis38 requested changes

2020-10-12 09:40 UTC, allandenis38 commented on content/en/docs/streams/security/security_best_practices.md
> +In line with security best practices, you can configure a password policy for administrator users in API Gateway Manager. Password policy refers to the size and complexity of the password, as well as
Remove Reference to API Gateway Manager

2020-10-12 09:40 UTC, allandenis38 commented on content/en/docs/streams/security/security_features.md
> +* Kubernetes secret data can be encrypted at rest. Raw encryption key can be stored within a KMS provider
Kubernetes secret**s**

2020-10-12 09:40 UTC, allandenis38 commented on content/en/docs/streams/security/security_features.md
> +* Data-at-rest is enabled by default for mariadb
mariadb => MariaDB

2020-10-12 09:40 UTC, allandenis38 commented on content/en/docs/streams/security/security_features.md
> +* Passwords for hazelcast and mariadb and are managed via kubernetes secrets
MariaDB

2020-10-12 09:40 UTC, allandenis38 commented on content/en/docs/streams/security/security_features.md
> +* A keyfile is required to enable data-at-rest encryption on mariadb
MariaDB

2020-10-12 09:40 UTC, allandenis38 commented on content/en/docs/streams/security/security_features.md
> +* A CA certificate, server certificate and a server key are required for TLS communication between Streams and the mariadb
MariaDB

2020-10-12 09:40 UTC, allandenis38 commented on content/en/docs/streams/security/security_features.md
> +* Certificates are stored and managed via kubernetes secrets
**K**ubernetes

2020-10-12 09:40 UTC, allandenis38 commented on content/en/docs/streams/security/security_features.md
> +* Connections between Streams microservice and database is SSL-secured by default.
microservice**s**

2020-10-12 09:40 UTC, allandenis38 commented on content/en/docs/streams/security/security_architecture.md
> +* MariaDB: RDBMS use to persist topics and subscriptions
used

2020-10-12 09:40 UTC, allandenis38 commented on content/en/docs/streams/security/security_architecture.md
> +The following diagram shows the product architecture from a security perspective.  The legend explains the security level on connections (SSL by default, always SSL, can be SSL, and so on) and on dat
SSL => TLS ?

2020-10-12 09:40 UTC, allandenis38 commented on content/en/docs/streams/security/security_best_practices.md
> +For a list of default ports that are opened by the API Gateway components, see [Default ports](/docs/apim_installation/apigtw_install/system_requirements/#default-ports).
Link to Streams doc instead

2020-10-12 09:40 UTC, allandenis38 commented on content/en/docs/streams/security/security_best_practices.md
> +Ensure the default protection mechanisms on sensitive files used by API Gateway and API Portal remain in place.  For example, the product’s files are installed with read, update, and delete privilege
Remove ref to API Gateway & API Portal

2020-10-12 09:40 UTC, allandenis38 commented on content/en/docs/streams/security/security_best_practices.md
> +
Not relevant for Streams

2020-10-12 09:40 UTC, allandenis38 commented on content/en/docs/streams/security/security_features.md
> +The following secure connections are available:
Trailing whitespace cause markdown lint issue

2020-10-12 09:40 UTC, allandenis38 commented on content/en/docs/streams/security/security_features.md
> +* All inbound connections to Streams are SSL-secured by default.
SSL => TLS ?

2020-10-12 09:40 UTC, allandenis38 commented on content/en/docs/streams/security/security_features.md
> +* Connections to other Axway products (for example, Axway API Gateway) can be SSL-secured.
SSL => TLS ?

2020-10-12 09:40 UTC, allandenis38 commented on content/en/docs/streams/security/security_features.md
> +* Kubernetes secret data can be encrypted at rest. Raw encryption key can be stored within a KMS provider
Missing "." at end of sentence

2020-10-12 09:45 UTC, dominiquemongelli commented on content/en/docs/streams/security/security_best_practices.md
> +In line with security best practices, you can configure a password policy for administrator users in API Gateway Manager. Password policy refers to the size and complexity of the password, as well as
I've removed the section as the password policy cannot be configured on Streams.

2020-10-13 12:53 UTC, benjaminranc commented on content/en/docs/streams/security/security_features.md
> +* Data-at-rest is enabled by default for MariaDB.
```suggestion
* Encrypted data-at-rest is enabled by default for MariaDB.
```

2020-10-13 13:53 UTC, closed without merging