Add documentation to install Streams using an external Kafka cluster and
Axway/streams-open-docs pull request #53
Opened 2020-12-17 18:52 UTC by benjaminranc

adapt Kafka documentation accordingly to the Helm chart refactoring

Thank you for your contribution to the Axway Streams documentation.

## Describe the changes

Add documentation to install Streams using an external Kafka cluster
Adapt Kafka install documentation accordingly to the Helm chart refactoring

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

## Checklist for approvers

_This section is to be filled out by project maintainers only._

Before approving this PR, please make sure it:

* [ ] Does not have conflicts with the base branch
* [ ] Is believed to be accurate (technical accuracy to be checked with an SME for PRs originating from outside R&D)
* [ ] Follows [Axway style](https://techweb.axway.com/confluence/display/RIE/Style+guide)
* [ ] Follows [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)
* [ ] Follows [best practices](https://axway-open-docs.netlify.com/docs/contribution_guidelines/bestpracticedevdoc/)
* [ ] Does not contain typos, grammatical errors, etc.
* [ ] Does not expose any sensitive information
* [ ] Passes the Markdown linter rules (automated via CI check)
* [ ] Does not contain broken links

2021-01-05 16:20 UTC, jfmarquet commented on content/en/docs/install/_index.md
> +* or specify `--set kafka.enabled=false` in the Helm Chart installation command.
make it one sentence

2021-01-05 16:20 UTC, jfmarquet commented on content/en/docs/install/_index.md
> +You must provide information to the Streams installation. You should edit the values.yaml file and set the `externalKafka` entry as follow:
switch to --set fashion

2021-01-05 16:20 UTC, jfmarquet commented on content/en/docs/install/_index.md
> +Currently, Streams works only with SASL/SCRAM authentication (using the SHA-512 hash functions) **and** TLS enable or neither.
TLS enabled, or none of the two.

2021-01-05 16:20 UTC, jfmarquet commented on content/en/docs/install/_index.md
> +    * Provide the user password using secret:
using a k8s secret:

2021-01-05 16:20 UTC, jfmarquet commented on content/en/docs/install/_index.md
> +* For no security:
For security disabled:

2021-01-05 16:20 UTC, jfmarquet commented on content/en/docs/install/_index.md
> +Currently, Streams works only with SASL/SCRAM authentication (using the SHA-512 hash functions) **and** TLS enable or neither.
same as previous note

2021-01-05 16:20 UTC, jfmarquet commented on content/en/docs/install/_index.md
> +    * Provide Kafka credentials using secret:
using a k8s secret:

2021-01-05 16:20 UTC, jfmarquet commented on content/en/docs/install/_index.md
> +Do not use all security disabled for production.
Disabling security is not recommended for production.

2021-01-06 08:28 UTC, jfmarquet approved these changes

2021-01-07 08:26 UTC, allandenis38 requested changes

2021-01-07 08:26 UTC, allandenis38 commented on content/en/docs/install/_index.md
> +| externalKafka.auth.clientUsername     | Username of the external Mariadb used by Streams (Only used when `kafka.enabled` set to false) | no | streams |
Name of the parameter `externalKafka.auth.clientUsername` refers to kafka but description refers to Mariadb.

2021-01-07 08:26 UTC, allandenis38 commented on content/en/docs/install/_index.md
> +#### Helm chart Kafka configuration
I got confused because of the section title,  expecting it to cover the configuration requirements for Kafka in our Helm chart but it fact this section covers configuration requirements when deploying Kafka on Kubernetes vs deploying Kafka outside the k8s cluster. We need to change the different titles to gain clarity.
Maybe External Kafka / Internal Kafka or Kafka outside Kubernetes / Kafka on Kubernetes
@lbadenhop Any thoughts ?

2021-01-07 09:11 UTC, benjaminranc commented on content/en/docs/install/_index.md
> +#### Helm chart Kafka configuration
Maybe Embedded Kafka / Externalized Kafka?

2021-01-07 20:33 UTC, lbadenhop commented on content/en/docs/install/_index.md
> +#### Helm chart Kafka configuration
Maybe Kafka outside Kubernetes / Kafka inside Kubernetes

2021-01-11 14:16 UTC, cremond commented on content/en/docs/install/_index.md
@benjaminranc @allandenis38 
Should you replace
`
By default, a Kafka cluster is automatically installed on your K8s cluster with the Streams Helm chart. But using an external one is recommended for production.`
`
To disable the Kafka installation, you can specify...
`
With something like
`By default, an embedded Kafka cluster is installed on your K8s cluster next to Streams. For production, we recommend using an externalized one instead.`
`
To disable the embedded Kafka installation, you can specify ...
`
for clarity and consistency ?
(just a suggestion)
(if so, same thing for mariadb)

2021-01-18 09:02 UTC, benjaminranc commented on content/en/docs/install/_index.md
I agree for adding "embedded"
For the rest, I don't really have an opinion, both solutions suit me

2021-01-19 10:34 UTC, allandenis38 commented on content/en/docs/install/_index.md
> +By default, a Kafka cluster is automatically installed on your K8s cluster with the Streams Helm chart. But using an external one is recommended for production.
```suggestion
By default, an embedded Kafka cluster is installed on your K8s cluster next to Streams. For production, we recommend that you use an externalized one instead.
```

2021-01-19 10:34 UTC, allandenis38 commented on content/en/docs/install/_index.md
> +The MariaDB database is automatically installed by default on your K8s cluster with the Streams Helm chart. But using an external one is recommended for production.
```suggestion
By default, an embedded MariaDB database is installed on your K8s cluster next to Streams. For production, we recommend that you use an externalized one instead.
```

2021-01-19 10:34 UTC, allandenis38 approved these changes

2021-01-19 10:37 UTC, allandenis38 commented
Hi @lbadenhop, this PR is ready for your review
Preview link: https://deploy-preview-53--streams-open-docs.netlify.app/

2021-01-19 20:50 UTC, lbadenhop commented on content/en/docs/install/_index.md
> +Then, according to your choice, configure your [externalized MariaDB](#externalized-mariadb-configuration) or your [automatically installed MariaDB](#embedded-mariadb-configuration).
```suggestion
Then, according to your choice, configure your [externalized MariaDB](#externalized-mariadb-configuration) or your [embedded MariaDB](#embedded-mariadb-configuration).
```

2021-01-19 20:52 UTC, lbadenhop commented on content/en/docs/install/_index.md
> +Then, according to your choice, configure your [externalized Kafka](#externalized-kafka-configuration) or your [automatically installed Kafka](#embedded-kafka-configuration).
```suggestion
Then, according to your choice, configure your [externalized Kafka](#externalized-kafka-configuration) or your [embedded Kafka](#embedded-kafka-configuration).
```

2021-01-19 20:58 UTC, lbadenhop commented on content/en/docs/install/_index.md
>  For security purpose, it's highly recommended to enable TLS communication between your database and Streams microservices. You can enable [One-Way TLS](https://mariadb.com/kb/en/securing-connections-
```suggestion
For security purposes, it's highly recommended to enable TLS communication between your database and Streams microservices. You can enable [One-Way TLS](https://mariadb.com/kb/en/securing-connections-for-client-and-server/#enabling-one-way-tls-for-mariadb-clients) or [Two-Way TLS](https://mariadb.com/kb/en/securing-connections-for-client-and-server/#enabling-two-way-tls-for-mariadb-clients).
```

2021-01-19 21:05 UTC, lbadenhop commented on content/en/docs/install/_index.md
> +For security purpose, it’s highly recommended to enable [SASL authentication](https://docs.confluent.io/current/kafka/authentication_sasl/index.html#authentication-with-sasl) and [TLS encryption](htt
```suggestion
For security purposes, it’s highly recommended to enable [SASL authentication](https://docs.confluent.io/current/kafka/authentication_sasl/index.html#authentication-with-sasl) and [TLS encryption](https://docs.confluent.io/current/kafka/encryption.html#encryption-with-ssl) for Kafka clients and brokers. You can enable both or neither.
```

2021-01-19 21:07 UTC, lbadenhop commented on content/en/docs/install/_index.md
> +Currently, Streams works only with SASL/SCRAM authentication (using the SHA-512 hash functions) **and** TLS enable or none of the two.
```suggestion
Currently, Streams works only with SASL/SCRAM authentication (using the SHA-512 hash functions) **and** TLS enabled or none of the two.
```

2021-01-19 21:11 UTC, lbadenhop commented on content/en/docs/install/_index.md
> +According to you choice, you must:
```suggestion
According to your choice, you must:
```

2021-01-19 21:16 UTC, lbadenhop commented on content/en/docs/install/_index.md
> +    * Provide a jks containing the kafka TLS truststore and its password:
```suggestion
    * Provide a JKS containing the Kafka TLS truststore and its password:
```

2021-01-19 21:20 UTC, lbadenhop commented on content/en/docs/install/_index.md
> +For security purpose, it’s highly recommended to enable [SASL authentication](https://docs.confluent.io/current/kafka/authentication_sasl/index.html#authentication-with-sasl) and [TLS encryption](htt
```suggestion
For security purposes, it’s highly recommended to enable [SASL authentication](https://docs.confluent.io/current/kafka/authentication_sasl/index.html#authentication-with-sasl) and [TLS encryption](https://docs.confluent.io/current/kafka/encryption.html#encryption-with-ssl) for Kafka clients and brokers. You can enable both or neither.
```

2021-01-19 21:21 UTC, lbadenhop commented on content/en/docs/install/_index.md
> +Currently, Streams works only with SASL/SCRAM authentication (using the SHA-512 hash functions) **and** TLS enable or none of the two.
```suggestion
Currently, Streams works only with SASL/SCRAM authentication (using the SHA-512 hash functions) **and** TLS enable or neither of the two.
```

2021-01-19 21:21 UTC, lbadenhop commented on content/en/docs/install/_index.md
> +According to you choice, you must:
```suggestion
According to your choice, you must:
```

2021-01-19 21:23 UTC, lbadenhop commented on content/en/docs/install/_index.md
> +        * They must all be integrated into Java Key Stores (JKS) files. Be careful as each broker needs its own keystore and a dedicated CN name matching the Kafka pod hostname as described in [bitna
```suggestion
        * They must all be integrated into Java Key Stores (JKS) files. Be careful, as each broker needs its own keystore and a dedicated CN name matching the Kafka pod hostname as described in [bitnami documentation](https://github.com/bitnami/charts/tree/master/bitnami/kafka#enable-security-for-kafka-and-zookeeper).
```

2021-01-19 21:25 UTC, lbadenhop commented on content/en/docs/install/_index.md
> +| externalKafka.auth.clientUsername     | Username of the externalized Kafka used by Streams (Only used when `kafka.enabled` set to false) | no | streams |
```suggestion
| externalKafka.auth.clientUsername     | Username of the externalized Kafka used by Streams (only used when `kafka.enabled` set to false) | no | streams |
```

2021-01-19 21:30 UTC, lbadenhop reviewed
See small edits

2021-01-20 08:01 UTC, merged