Draft: Refactor helm
Axway/streams-open-docs pull request #55
Opened 2021-01-15 10:24 UTC by cremond

Thank you for your contribution to the Axway Streams documentation.

## Describe the changes

Enter a brief description of your changes here to communicate to the maintainers what you changed and why.

## Checklist for contributors

Before submitting this PR, please make sure:

* [x ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ x] You have signed the [Axway CLA](https://cla.axway.com/)
* [x ] You have verified the technical accuracy of your change
* [x ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [x ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

## Checklist for approvers

_This section is to be filled out by project maintainers only._

Before approving this PR, please make sure it:

* [ ] Does not have conflicts with the base branch
* [ ] Is believed to be accurate (technical accuracy to be checked with an SME for PRs originating from outside R&D)
* [ ] Follows [Axway style](https://techweb.axway.com/confluence/display/RIE/Style+guide)
* [ ] Follows [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)
* [ ] Follows [best practices](https://axway-open-docs.netlify.com/docs/contribution_guidelines/bestpracticedevdoc/)
* [ ] Does not contain typos, grammatical errors, etc.
* [ ] Does not expose any sensitive information
* [ ] Passes the Markdown linter rules (automated via CI check)
* [ ] Does not contain broken links

2021-01-18 09:22 UTC, benjaminranc requested changes

2021-01-18 09:22 UTC, benjaminranc commented on content/en/docs/install/_index.md
> +enabled: false
```suggestion
  enabled: false
```

2021-01-19 17:55 UTC, cremond commented
Hello @allandenis38 this pull request has been reviewed by @benjaminranc and is ready for your review. It is about a change of a few flags (including the embeddedMariadb embeddedKafka changes when it comes to _ our code_) due to a massive refactoring of helm. Watch out for the handling of k8s.yourdomain.tld which has been modified to hopefully make it less confusing. The jira ticket is STREAMS-1440.

2021-01-20 17:15 UTC, allandenis38 approved these changes

2021-01-20 17:16 UTC, allandenis38 commented
@lbadenhop PR ready for your review
Preview: https://deploy-preview-55--streams-open-docs.netlify.app/

2021-01-20 19:56 UTC, lbadenhop commented on content/en/docs/install/_index.md
> +Then you must provide information to the Streams installation. You should edit the `values.yaml` file and set the `externalizedMariadb` entry as follow:
```suggestion
Then you must provide information to the Streams installation. You should edit the `values.yaml` file and set the `externalizedMariadb` entry as follows:
```

2021-01-20 19:58 UTC, lbadenhop commented on content/en/docs/install/_index.md
>  * For Two-Way TLS:
```suggestion
* For two-way TLS:
```

2021-01-20 20:00 UTC, lbadenhop commented on content/en/docs/install/_index.md
>  You can follow the official documentation provided by Mariadb [Certificate Creation with OpenSSL](https://mariadb.com/kb/en/certificate-creation-with-openssl/) to generate self-signed certificate. Ma
```suggestion
See the official documentation provided by MariaDB [Certificate Creation with OpenSSL](https://mariadb.com/kb/en/certificate-creation-with-openssl/) to generate self-signed certificates. Make sure to set the Common Name correctly.
```

2021-01-20 20:07 UTC, lbadenhop commented on content/en/docs/install/_index.md
> +For this entire documentation we are using k8s.yourdomain.tld as an _example_ value.
```suggestion
Throughout this documentation, we are using k8s.yourdomain.tld as an _example_ value.
```

2021-01-20 20:09 UTC, lbadenhop reviewed
See suggestions

2021-01-21 07:25 UTC, merged