Streams 1569 database guidelines
Axway/streams-open-docs pull request #57
Opened 2021-01-19 09:19 UTC by jfmarquet

Thank you for your contribution to the Axway Streams documentation.

## Describe the changes

Add database configuration guidelines and align doc with current state of the platform.

## Checklist for contributors

Before submitting this PR, please make sure:

* [x] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [x] You have signed the [Axway CLA](https://cla.axway.com/)
* [x] You have verified the technical accuracy of your change
* [x] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [x] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

## Checklist for approvers

_This section is to be filled out by project maintainers only._

Before approving this PR, please make sure it:

* [ ] Does not have conflicts with the base branch
* [ ] Is believed to be accurate (technical accuracy to be checked with an SME for PRs originating from outside R&D)
* [ ] Follows [Axway style](https://techweb.axway.com/confluence/display/RIE/Style+guide)
* [ ] Follows [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)
* [ ] Follows [best practices](https://axway-open-docs.netlify.com/docs/contribution_guidelines/bestpracticedevdoc/)
* [ ] Does not contain typos, grammatical errors, etc.
* [ ] Does not expose any sensitive information
* [ ] Passes the Markdown linter rules (automated via CI check)
* [ ] Does not contain broken links

2021-01-20 09:00 UTC, guillaumelamirand commented on content/en/docs/architecture/_index.md
> +| helm release internal info    | helm                      | helm.sh/release.v1                  |
It seeems that most of the secret name are invalid and are missing the prefix 'streams-'

- streams-database-passwords-secret
- streams-database-secret
- streams-kafka-passwords-secret
- streams-kafka-client-jks-secret
- streams-ingress-tls-secret

2021-01-20 11:07 UTC, allandenis38 requested changes

2021-01-20 11:07 UTC, allandenis38 commented on content/en/docs/architecture/_index.md
> +    * One may also take into account the load expected on the platform which may lead to increase the number of microservice replicas. It is recommended to compute the `streams_db_connections` with t
```suggestion
    * One may also take into account the expected load on the platform, which may lead to an increase in the number of microservice replicas. It is recommended to compute the `streams_db_connections` with the highest number of pod replicas expected so that the platform can properly handle peak load.
```

2021-01-20 14:10 UTC, allandenis38 approved these changes

2021-01-20 14:10 UTC, allandenis38 commented
@lbadenhop PR is ready for your review
Preview: https://deploy-preview-57--streams-open-docs.netlify.app/

2021-01-20 18:09 UTC, lbadenhop commented on content/en/docs/architecture/_index.md
> +Because the technology chosen, Docker and Kubernetes, are portable across on-premise environments and many cloud providers, most of the information in this guide should apply to those environments. B
```suggestion
Because Docker and Kubernetes are portable across on-premise environments and many cloud providers, most of the information in this guide should apply to those environments. However, we've also included specific recommendations for AWS, as it is one of the most common deployment targets.
```

2021-01-20 18:19 UTC, lbadenhop commented on content/en/docs/architecture/_index.md
> +A load balancer is required in front of the cluster. We use the Kubernetes object called ingress controller that is responsible for fulfilling the ingress rules. A NGINX ingress controller is, by def
```suggestion
A load balancer is required in front of the cluster. We use the Kubernetes object called ingress controller that is responsible for fulfilling the ingress rules. A NGINX ingress controller is, by default, deployed with our Helm chart installation. For better performance, we recommend you to use a L4 Load balancer. See your Cloud provider documentation to configure it (e.g. [AWS Load Balancing](https://docs.aws.amazon.com/eks/latest/userguide/load-balancing.html)).
```

2021-01-20 18:27 UTC, lbadenhop commented on content/en/docs/architecture/_index.md
>  Kubernetes Role-based access control ([RBAC](https://kubernetes.io/docs/reference/access-authn-authz/rbac/)) is a method of regulating access to your Kubernetes cluster and resources based on the rol
```suggestion
Kubernetes' role-based access control ([RBAC](https://kubernetes.io/docs/reference/access-authn-authz/rbac/)) is a method of regulating access to your Kubernetes cluster and resources based on the roles of individual users within an enterprise. Streams requires RBAC to be enabled for secrets management and third-party dependencies:
```

2021-01-20 18:32 UTC, lbadenhop commented on content/en/docs/architecture/_index.md
> +For 3rd parties pods (NGINX, Kafka, Zookeeper and MariaDB) you have to define it for each of them:
```suggestion
You must define it for each of the 3rd party pods (NGINX, Kafka, Zookeeper and MariaDB):
```

2021-01-20 18:44 UTC, lbadenhop commented on content/en/docs/architecture/_index.md
> +We use the NGINX Ingress Controller to expose both management and subscription APIs. NGINX Ingress Controller automatically creates a Load Balancer in the cloud provider infrastructure so that the AP
```suggestion
We use the NGINX Ingress Controller to expose both management and subscription APIs. NGINX Ingress Controller automatically creates a load balancer in the cloud provider infrastructure so that the APIs can be reached from the outside using the load balancer DNS hostname. Once known, this hostname must be updated in the ingress resource thanks to the value of the helm parameter `ingress.host`.
```

2021-01-20 18:48 UTC, lbadenhop commented on content/en/docs/architecture/_index.md
> +We use the NGINX Ingress Controller to expose both management and subscription APIs. NGINX Ingress Controller automatically creates a Load Balancer in the cloud provider infrastructure so that the AP
Is the hostname updated in parameter `ingress.host`? If so, I recommend: Once known, this hostname must be updated in the ingress resource helm parameter `ingress.host`.

2021-01-20 18:48 UTC, lbadenhop commented on content/en/docs/architecture/_index.md
> +SSL/TLS is enabled by default on NGINX ingress controller unless you have explicitly disabled it (`ingress.tlsenabled=false`).
```suggestion
SSL/TLS is enabled by default on NGINX Ingress Controller unless you have explicitly disabled it (`ingress.tlsenabled=false`).
```

2021-01-20 18:58 UTC, lbadenhop commented on content/en/docs/architecture/_index.md
>  The ingress controller handles SSL/TLS termination with to the correct certificate/secret (more setup details)
```suggestion
The ingress controller handles SSL/TLS termination with the correct certificate/secret (more setup details).
```

2021-01-20 19:01 UTC, lbadenhop commented on content/en/docs/architecture/_index.md
>  The ingress controller handles SSL/TLS termination with to the correct certificate/secret (more setup details)
I don't understand the following: (more setup details). Is this an internal note meaning that more setup details should be provided by the author?

2021-01-20 19:04 UTC, lbadenhop commented on content/en/docs/architecture/_index.md
>  Here is the list of secrets related to Streams installation:
```suggestion
The following list of secrets relate to the Streams installation:
```

2021-01-20 19:08 UTC, lbadenhop commented on content/en/docs/architecture/_index.md
> +    * Each microservice which depends on the database maintains a connection pool of `maximumPoolSize` threads (default: 10). Connections are established using user _streams_. When a database call ne
```suggestion
    * Each microservice, which depends on the database, maintains a connection pool of `maximumPoolSize` threads (default: 10). Connections are established using user _streams_. When a database call needs to be performed (e.g. topic creation, liveness probe...), either an existing idle connection is available and used for this call, or all the connections in the pool are already in use and the call is queued during `connectionTimeout` (default: 25s).
```

2021-01-20 19:10 UTC, lbadenhop commented on content/en/docs/architecture/_index.md
> +For best performances with Streams, MariaDB should be configured as follows:
```suggestion
For the best performance with Streams, MariaDB should be configured as follows:
```

2021-01-20 19:14 UTC, lbadenhop commented on content/en/docs/architecture/_index.md
> +    * 5 minutes is a good value, so reconnection are not too frequent and zombie connections due to potential k8s pod or node crash can be managed fast enough.
```suggestion
    * 5 minutes is recommended so that reconnections are not too frequent and zombie connections that are due to potential k8s pod / node crashes can be managed in a timely manner.
```

2021-01-20 19:15 UTC, lbadenhop commented on content/en/docs/architecture/_index.md
> +    * Keep in mind to set your Streams installation `maxLifetime` below this value. For instance, a microservice connection will die after remaining `maxLifetime` seconds in the pool, but if a pod cr
```suggestion
    * Remember to set your Streams installation `maxLifetime` below this value. For instance, a microservice connection will die after remaining `maxLifetime` seconds in the pool, but if a pod crashes and the connection cannot be closed properly after `maxLifetime`, it will eventually be destroyed after `wait-timeout`.
```

2021-01-20 19:16 UTC, lbadenhop commented on content/en/docs/architecture/_index.md
> +    * One may also take into account the expected load on the platform, which may lead to an increase in the number of microservice replicas. It is recommended to compute the `streams_db_connections`
```suggestion
    * Also take into account the expected load on the platform, which may lead to an increase in the number of microservice replicas. It is recommended to compute the `streams_db_connections` with the highest number of pod replicas expected so that the platform can properly handle peak load.
```

2021-01-20 19:18 UTC, lbadenhop commented on content/en/docs/architecture/_index.md
> +    Several connections are also established by MariaDB itself (5 for InnoDB and 1 for replication).
```suggestion
    Several connections are also established by MariaDB (five for InnoDB and one for replication).
```

2021-01-20 19:21 UTC, lbadenhop commented on content/en/docs/install/_index.md
> +These values of the embedded MariaDB configuration can be updated:
```suggestion
The following embedded MariaDB configuration values can be updated:
```

2021-01-20 19:25 UTC, lbadenhop commented on content/en/docs/install/_index.md
> +{{< alert title="Note" >}}Please, refer to the [MariaDB considerations](/docs/architecture#mariadb-considerations) documentation for further details.{{< /alert >}}
```suggestion
{{< alert title="Note" >}}Refer to the [MariaDB considerations](/docs/architecture#mariadb-considerations) documentation for further details.{{< /alert >}}
```

2021-01-20 19:26 UTC, lbadenhop commented on content/en/docs/install/_index.md
> +* The `wait-timeout` variable can be updated by setting the [Helm parameters](#helm-parameters) `embeddedMariadb.waitTimeout`.
```suggestion
* `wait-timeout` - update by setting the [Helm parameters](#helm-parameters) `embeddedMariadb.waitTimeout`.
```

2021-01-20 19:27 UTC, lbadenhop commented on content/en/docs/install/_index.md
> +* The `max-connections` variable can be updated by setting the [Helm parameters](#helm-parameters) `embeddedMariadb.maxConnections`.
```suggestion
* `max-connections` - updated by setting the [Helm parameters](#helm-parameters) `embeddedMariadb.maxConnections`.
```

2021-01-20 19:29 UTC, lbadenhop commented on content/en/docs/install/_index.md
> +SSL/TLS is enabled by default on the embedded Ingress controller. If you don't provide any certificate, SSL will be enabled thanks to a NGINX embedded fake SSL certificate.
```suggestion
SSL/TLS is enabled by default on the embedded Ingress controller. If you don't provide a certificate, SSL will be enabled with a NGINX embedded fake SSL certificate.
```

2021-01-20 19:30 UTC, lbadenhop reviewed
See suggested changes

2021-01-20 19:35 UTC, allandenis38 commented on content/en/docs/architecture/_index.md
>  The ingress controller handles SSL/TLS termination with to the correct certificate/secret (more setup details)
@jfmarquet @benjaminranc Need your input on this as I do not understand it neither.

2021-01-21 08:30 UTC, allandenis38 approved these changes

2021-01-21 08:30 UTC, allandenis38 commented on content/en/docs/architecture/_index.md
> +The ingress controller handles SSL/TLS termination with a certificate manage with a k8s secret (refer to the [Ingress TLS settings](/docs/install#ingress-tls-settings) documentation for further detai
```suggestion
The ingress controller handles the SSL/TLS termination thanks to a certificate stored in a k8s secret (refer to the [Ingress TLS settings](/docs/install#ingress-tls-settings) documentation for further details).
```

2021-01-21 13:41 UTC, merged