STREAMS-1597 Restructure Install
Axway/streams-open-docs pull request #66
Opened 2021-02-18 22:22 UTC by lbadenhop

Thank you for your contribution to the Axway Streams documentation.

## Describe the changes

Broke out Install topics:
Install (index)
Helm parameters
Upgrade
Uninstall
Backup and disaster recovery
Note: I did not address the heading issue in the install topic. I will do that next.

## Checklist for contributors

Before submitting this PR, please make sure:

* [x] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [x] You have signed the [Axway CLA](https://cla.axway.com/)
* [x] You have verified the technical accuracy of your change
* [x] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [x] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

## Checklist for approvers

_This section is to be filled out by project maintainers only._

Before approving this PR, please make sure it:

* [ ] Does not have conflicts with the base branch
* [ ] Is believed to be accurate (technical accuracy to be checked with an SME for PRs originating from outside R&D)
* [ ] Follows [Axway style](https://techweb.axway.com/confluence/display/RIE/Style+guide)
* [ ] Follows [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)
* [ ] Follows [best practices](https://axway-open-docs.netlify.com/docs/contribution_guidelines/bestpracticedevdoc/)
* [ ] Does not contain typos, grammatical errors, etc.
* [ ] Does not expose any sensitive information
* [ ] Passes the Markdown linter rules (automated via CI check)
* [ ] Does not contain broken links

2021-02-18 22:31 UTC, lbadenhop commented
@allandenis38 Ready for your review

2021-02-19 08:23 UTC, guillaumelamirand commented
Just a comment your branch has been created from develop, so you should apply the PR over develop branch instead of master.

2021-03-01 14:08 UTC, allandenis38 commented
@lbadenhop FYI as mentioned by @guillaumelamirand previous comment I changed the target branch to develop.

2021-03-01 14:10 UTC, allandenis38 approved these changes

2021-03-01 14:11 UTC, allandenis38 commented
@lbadenhop I am fine with the proposed restructuring of the install section.

2021-03-04 02:18 UTC, lbadenhop commented
@allandenis38 Ready for your review. Also fixed broken link on index page. I cannot validate the link to "contribution guidelines" because Netlify for Streams seems to be unavailable.

2021-03-15 12:28 UTC, allandenis38 requested changes

2021-03-15 12:28 UTC, allandenis38 commented on content/en/docs/install/_index.md
>  Streams ships with monitoring. You can activate metrics with the parameters listed in [Monitoring parameters](#monitoring-parameters),
```suggestion
Streams ships with monitoring. You can activate metrics with the parameters listed in [Monitoring parameters](/docs/install/helm-parameters/#monitoring-parameters),
```

2021-03-15 12:29 UTC, allandenis38 approved these changes

2021-03-15 12:30 UTC, merged