STREAMS-935-metrics feat : add a page describing the custom metrics o…
Axway/streams-open-docs pull request #70
Opened 2021-03-29 15:45 UTC by cremond

…f Streams

Thank you for your contribution to the Axway Streams documentation.

## Describe the changes

I have added a description of the metrics provided by Streams so that users can monitor their installations

## Checklist for contributors

Before submitting this PR, please make sure:

* [x ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [x ] You have signed the [Axway CLA](https://cla.axway.com/)
* [x ] You have verified the technical accuracy of your change
* [x ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ x] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

## Checklist for approvers

_This section is to be filled out by project maintainers only._

Before approving this PR, please make sure it:

* [ ] Does not have conflicts with the base branch
* [ ] Is believed to be accurate (technical accuracy to be checked with an SME for PRs originating from outside R&D)
* [ ] Follows [Axway style](https://techweb.axway.com/confluence/display/RIE/Style+guide)
* [ ] Follows [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)
* [ ] Follows [best practices](https://axway-open-docs.netlify.com/docs/contribution_guidelines/bestpracticedevdoc/)
* [ ] Does not contain typos, grammatical errors, etc.
* [ ] Does not expose any sensitive information
* [ ] Passes the Markdown linter rules (automated via CI check)
* [ ] Does not contain broken links

2021-03-29 19:55 UTC, allandenis38 requested changes

2021-03-29 19:55 UTC, allandenis38 commented on content/en/docs/metrics.md
> +Although we assume your are familiare with the Prometheus metrics format, here is a quick explanation of the main
```suggestion
Although we assume your are familiar with the Prometheus metrics format, here is a quick explanation of the main
```

2021-03-29 19:55 UTC, allandenis38 commented on content/en/docs/metrics.md
> +metrics types produced by [micrometer](https://micrometer.io/docs/registry/prometheus) and how to make use of them :
```suggestion
metrics types produced by [micrometer](https://micrometer.io/docs/registry/prometheus) and how to make use of them:
```

2021-03-29 19:55 UTC, allandenis38 commented on content/en/docs/metrics.md
> +| Gauge   | streams_global_topics                   | Number of topics in total on Streams                      |  |
```suggestion
| Gauge   | streams_global_topics                   | Total number of Streams topics                       |  |
```

2021-03-29 19:55 UTC, allandenis38 commented on content/en/docs/metrics.md
> +| Gauge   | streams_global_persistent_subscriptions | Number of persistent subscriptions in total on Streams    | streams_global_persistent_subscriptions{subscription_status="active"} |
```suggestion
| Gauge   | streams_global_persistent_subscriptions | Total number of persistent subscriptions    | streams_global_persistent_subscriptions{subscription_status="active"} |
```

2021-03-29 19:55 UTC, allandenis38 commented on content/en/docs/metrics.md
> +The keyword global here refers to the fact that some metrics should have the same value everywhere,
```suggestion
The keyword global refers to the scope of the metrics. Global metrics are reported by all instances of the same type of service and will have the same value regardless of the service instance that reports them,
```

2021-03-29 19:55 UTC, allandenis38 commented on content/en/docs/metrics.md
> +whereas the others only give information about the service which reported them.
```suggestion
whereas the others only give information about the service instance which reported them.
```

2021-03-29 19:57 UTC, allandenis38 commented
Hi @lbadenhop, you can review this MR. Don't hesitate to make changes on my suggestions.

2021-03-29 23:52 UTC, lbadenhop commented on content/en/docs/metrics.md
> +* Timer : A timer records tasks durations by keeping a counter of completed tasks, and a counter of their cumulated time.
```suggestion
* Timer: A timer records task durations by keeping a counter of completed tasks, and a counter of their cumulated time.
```

2021-03-29 23:56 UTC, lbadenhop commented on content/en/docs/metrics.md
> +We have implemented the following custom metrics. All of those have labels describing the service name, type,
```suggestion
The following custom metrics have been implemented. They include labels describing the service name, type,
```

2021-03-30 00:01 UTC, lbadenhop commented on content/en/docs/metrics.md
> +Our frameworks provide a lot of additional metrics. However,
```suggestion
Our frameworks provides additional metrics; however,
```

2021-03-30 00:07 UTC, lbadenhop commented on content/en/docs/metrics.md
> +* http\_client\_request\_seconds : timer of the web requests _emitted_ by Streams (i.e. polling or webhook).
```suggestion
* http\_client\_request\_seconds : timer of the web requests _emitted_ by Streams (i.e., polling or webhook).
```

2021-03-30 00:07 UTC, lbadenhop commented on content/en/docs/metrics.md
> +* http\_server\_requests\_seconds : timer of the web requests _received_ and handled by Streams (i.e. REST api, self health-check, and http-post).
```suggestion
* http\_server\_requests\_seconds : timer of the web requests _received_ and handled by Streams (i.e., REST API, self health-check, and http-post).
```

2021-03-30 00:14 UTC, lbadenhop commented on content/en/docs/metrics.md
> +a counter of the number of the number of requests, and here a gauge of the maximum request time over the latest period of time.
```suggestion
a counter of the number of requests, and a gauge of the maximum request time over the latest period of time.
```

2021-03-30 00:16 UTC, lbadenhop commented on content/en/docs/metrics.md
> +For instance, to get the average incoming requests processing time, you could plot :
```suggestion
For example, to get the average incoming requests' processing time, you could plot :
```

2021-03-30 00:17 UTC, lbadenhop commented on content/en/docs/metrics.md
> +we recommend you pay attention to the following timers in particular.
```suggestion
we recommend you pay attention to the following timers:
```

2021-03-30 00:19 UTC, lbadenhop approved these changes

2021-03-30 06:43 UTC, allandenis38 approved these changes

2021-03-30 06:52 UTC, merged