STREAMS-1866 update Nginx helm chart url and parameters
Axway/streams-open-docs pull request #75
Opened 2021-04-16 16:10 UTC by benjaminranc

Thank you for your contribution to the Axway Streams documentation.

## Describe the changes

We change the Nginx Helm chart to the Bitnami Nginx Helm chart. We have to update url and parameters accrordingly.

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

## Checklist for approvers

_This section is to be filled out by project maintainers only._

Before approving this PR, please make sure it:

* [ ] Does not have conflicts with the base branch
* [ ] Is believed to be accurate (technical accuracy to be checked with an SME for PRs originating from outside R&D)
* [ ] Follows [Axway style](https://techweb.axway.com/confluence/display/RIE/Style+guide)
* [ ] Follows [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)
* [ ] Follows [best practices](https://axway-open-docs.netlify.com/docs/contribution_guidelines/bestpracticedevdoc/)
* [ ] Does not contain typos, grammatical errors, etc.
* [ ] Does not expose any sensitive information
* [ ] Passes the Markdown linter rules (automated via CI check)
* [ ] Does not contain broken links

2021-04-30 09:01 UTC, cremond commented
@benjaminranc everything here seems ok to me

2021-04-30 12:59 UTC, andreamussap commented
@benjaminranc any idea when this PR should be ready for review?

2021-04-30 13:50 UTC, benjaminranc commented
> @benjaminranc any idea when this PR should be ready for review?

@andreamussap I was waiting for a peer review (done today). I set in ready.

2021-04-30 13:56 UTC, guillaumelamirand requested changes

2021-04-30 13:56 UTC, guillaumelamirand commented on content/en/docs/architecture/_index.md
> +| 2                  | 2   | 2048 MB | n/a       | 8 GB        |
Why do we need so much memory increasing?

2021-04-30 14:03 UTC, benjaminranc commented on content/en/docs/architecture/_index.md
> +| 2                  | 2   | 2048 MB | n/a       | 8 GB        |
It has not been increased during this story. But we probably forgot to update the documentation because these are the resources defined in our HA values

2021-05-03 07:18 UTC, guillaumelamirand approved these changes

2021-05-03 14:30 UTC, lbadenhop approved these changes

2021-05-03 14:32 UTC, merged