Streams 1849 at least once qos
Axway/streams-open-docs pull request #76
Opened 2021-04-27 09:29 UTC by guillaumelamirand

Thank you for your contribution to the Axway Streams documentation.

## Describe the changes

Enter a brief description of your changes here to communicate to the maintainers what you changed and why.

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

## Checklist for approvers

_This section is to be filled out by project maintainers only._

Before approving this PR, please make sure it:

* [ ] Does not have conflicts with the base branch
* [ ] Is believed to be accurate (technical accuracy to be checked with an SME for PRs originating from outside R&D)
* [ ] Follows [Axway style](https://techweb.axway.com/confluence/display/RIE/Style+guide)
* [ ] Follows [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)
* [ ] Follows [best practices](https://axway-open-docs.netlify.com/docs/contribution_guidelines/bestpracticedevdoc/)
* [ ] Does not contain typos, grammatical errors, etc.
* [ ] Does not expose any sensitive information
* [ ] Passes the Markdown linter rules (automated via CI check)
* [ ] Does not contain broken links

2021-04-27 13:25 UTC, allandenis38 requested changes

2021-04-27 13:25 UTC, allandenis38 commented on content/en/docs/subscribers/_index.md
> +Streams has a strong requirement in term of quality but also in term of the performance. To get the best of those two aspects, Streams garanties **at least once** delivery, such as clients are certai
```suggestion
Streams has strong requirements in terms of both quality of service and performance. To provide the best trade-off between these two conflicting aspects, Streams supports **at-least-once** delivery semantic.
```

2021-04-27 13:25 UTC, allandenis38 commented on content/en/docs/subscribers/_index.md
> +We ensure this quality of services by keeping for each subscriptions the last event id delivered, in order to resume from it in case of reconnection. The mechanism is internaly managed by Streams for
```suggestion
We ensure this quality of service by keeping the last event id delivered for each subscription, in order to resume from it in the event of failure (e.g., network failure, component failure). The mechanism is managed internally by Streams for persistent subscribers such as Webhook or Kafka subscribers but depends on a client side mechanism for SSE. Refer to [Last-Event-Id](../subscribers/subscriber-sse#last-event-id) section for details.
```

2021-04-27 13:25 UTC, allandenis38 commented on content/en/docs/subscribers/subscriber-sse.md
> +Each messages sent by Streams are uniquely identified, so using the built-in header `Last-Event-id` after a reconnection, the client can tell to Streams where in the events streams to resume. Such me
```suggestion
Each message sent by Streams is uniquely identified. Using the built-in header `Last-Event-Id` after reconnecting, the client can tell Streams where in the events streams to resume. Such mechanism is automatically integrated in most clients but you can also achieve it using curl command, using the example given above it will be:
```

2021-04-30 13:18 UTC, allandenis38 approved these changes

2021-05-03 14:37 UTC, lbadenhop commented on content/en/docs/subscribers/_index.md
> +We ensure this quality of service by keeping the last event id delivered for each subscription, in order to resume from it in case of failure (e.g., network failure, component failure). The mechanism
```suggestion
We ensure this quality of service by keeping the last event id delivered for each subscription, in order to resume from it in case of failure (e.g., network failure, component failure). The mechanism is internally managed by Streams for persistent subscribers, such as Webhook or Kafka subscribers, but depends on a client side mechanism for SSE. Refer to [Last-Event-Id](../subscribers/subscriber-sse#last-event-id) section for details.
```

2021-05-03 14:42 UTC, lbadenhop commented on content/en/docs/subscribers/subscriber-sse.md
> +Server-Sent Events (SSE) is part of the HTML5 standard. SSEs are sent over traditional HTTP, so it doesn't require a special protocol to get working. SSE embedded important features such event identi
```suggestion
Server-Sent Events (SSE) is part of the HTML5 standard. SSEs are sent over traditional HTTP, so they don't require a special protocol to get working. SSE embedded important features, such event identifier, automatically reconnect or the have the ability to manage heterogeneous events.
```

2021-05-03 14:47 UTC, guillaumelamirand commented on content/en/docs/subscribers/subscriber-sse.md
> +Server-Sent Events (SSE) is part of the HTML5 standard. SSEs are sent over traditional HTTP, so it doesn't require a special protocol to get working. SSE embedded important features such event identi
on the last sentence, "the have the ability" it looks like a word is missing, isn't it?

2021-05-03 14:49 UTC, lbadenhop commented on content/en/docs/subscribers/subscriber-sse.md
> +Each message sent by Streams is uniquely identified. Using the built-in header `Last-Event-Id` after reconnecting, the client can tell Streams where in the events streams to resume. Such mechanism is
```suggestion
Each message sent by Streams is uniquely identified. Using the built-in header `Last-Event-Id` after reconnecting, the client can tell Streams where in the events streams to resume. This mechanism is automatically integrated in most clients, but you can also achieve it using the curl command:
```

2021-05-03 14:50 UTC, lbadenhop reviewed
See comments

2021-05-03 14:52 UTC, lbadenhop commented
@guillaumelamirand Andrea is no longer assigned to Streams. Please remove her from reviewers in the furture.

2021-05-03 14:55 UTC, guillaumelamirand commented
> @guillaumelamirand Andrea is no longer assigned to Streams. Please remove her from reviewers in the future.

We have been told that Andrea is taking over you since 21th of April, so we/she update everything in this way.

2021-05-03 14:59 UTC, lbadenhop commented
@guillaumelamirand OK, I had not been told this. I'll leave the outstanding PR for her to review, but she probably doesn't need to look at the PRs I already reviewed this morning. Thanks.

2021-05-05 21:28 UTC, lbadenhop commented on content/en/docs/subscribers/subscriber-sse.md
> +Server-Sent Events (SSE) is part of the HTML5 standard. SSEs are sent over traditional HTTP, so it doesn't require a special protocol to get working. SSE embedded important features such event identi
Server-Sent Events (SSE) is part of the HTML5 standard. SSEs are sent over traditional HTTP, so they don't require a special protocol to work. SSE embedded important features, such event identifier, either automatically reconnect or they have the ability to manage heterogeneous events.

2021-05-06 07:36 UTC, guillaumelamirand commented on content/en/docs/subscribers/subscriber-sse.md
> +Server-Sent Events (SSE) is part of the HTML5 standard. SSEs are sent over traditional HTTP, so it doesn't require a special protocol to get working. SSE embedded important features such event identi
Ok I fixed it.

2021-05-06 07:39 UTC, guillaumelamirand commented
@andreamussap I have fixed every comment I let you merge it.

2021-05-10 14:54 UTC, andreamussap commented on content/en/docs/subscribers/subscriber-sse.md
> +Server-Sent Events (SSE) is part of the HTML5 standard. SSEs are sent over traditional HTTP, so they don't require a special protocol to work. SSE embedded important features, such event identifier,
"**SSE embedded important features, such event identifier...**" --> This is a bit confusing to me. Do you mean, "SSE includes important features, such as, `Last-Event-ID header` event identifier, which either automatically reconnects a broken connection or _can manage heterogeneous events_."

(...can manage heterogeneous events ???) - even with suggestion above, this last part is still not clear

2021-05-10 15:19 UTC, allandenis38 commented on content/en/docs/subscribers/subscriber-sse.md
> +Server-Sent Events (SSE) is part of the HTML5 standard. SSEs are sent over traditional HTTP, so they don't require a special protocol to work. SSE embedded important features, such event identifier,
@andreamussap Here my proposal: SSE includes important features, such as, `Last-Event-ID` header support, automatic reconnection and heterogeneous event handling.

2021-05-11 11:47 UTC, andreamussap approved these changes

2021-05-11 11:47 UTC, merged