STREAMS-2077 doc() : explain how to accept the general conditions
Axway/streams-open-docs pull request #93
Opened 2021-06-09 09:39 UTC by cremond

…installation

Thank you for your contribution to the Axway Streams documentation.

## Describe the changes

Enter a brief description of your changes here to communicate to the maintainers what you changed and why.

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

## Checklist for approvers

_This section is to be filled out by project maintainers only._

Before approving this PR, please make sure it:

* [ ] Does not have conflicts with the base branch
* [ ] Is believed to be accurate (technical accuracy to be checked with an SME for PRs originating from outside R&D)
* [ ] Follows [Axway style](https://techweb.axway.com/confluence/display/RIE/Style+guide)
* [ ] Follows [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)
* [ ] Follows [best practices](https://axway-open-docs.netlify.com/docs/contribution_guidelines/bestpracticedevdoc/)
* [ ] Does not contain typos, grammatical errors, etc.
* [ ] Does not expose any sensitive information
* [ ] Passes the Markdown linter rules (automated via CI check)
* [ ] Does not contain broken links

2021-06-09 09:48 UTC, guillaumelamirand requested changes

2021-06-09 09:48 UTC, guillaumelamirand commented on content/en/docs/install/_index.md
> +To accept them, you can set the helm value `acceptGeneralConditions` to `yes` and proceed with the installation.
"you have to"

2021-06-09 09:52 UTC, cremond commented on content/en/docs/install/_index.md
> +To accept them, you can set the helm value `acceptGeneralConditions` to `yes` and proceed with the installation.
done

2021-06-09 12:30 UTC, guillaumelamirand commented on content/en/docs/install/_index.md
> +### General Conditions for License/Subscription
Réduire le niveau du titre a ##

2021-06-09 15:22 UTC, cremond commented on content/en/docs/install/_index.md
> +### General Conditions for License/Subscription
done

2021-06-11 09:03 UTC, guillaumelamirand approved these changes

2021-06-14 08:34 UTC, guillaumelamirand commented
@andreamussap Could you please review and merge this one ? Thanks

2021-06-14 10:12 UTC, merged